/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutLayout: typeof import('./../components/layouts/AboutLayout.vue')['default']
    AsideAvatar: typeof import('./../components/aside/AsideAvatar.vue')['default']
    AsideBox: typeof import('./../components/aside/AsideBox.vue')['default']
    AsideCount: typeof import('./../components/aside/AsideCount.vue')['default']
    AsideLabel: typeof import('./../components/aside/AsideLabel.vue')['default']
    AsideMenu: typeof import('./../components/aside/AsideMenu.vue')['default']
    AsideSearch: typeof import('./../components/aside/AsideSearch.vue')['default']
    AsideSocialize: typeof import('./../components/aside/AsideSocialize.vue')['default']
    BlogLayout: typeof import('./../components/layouts/BlogLayout.vue')['default']
    ContentImage: typeof import('./../components/md/ContentImage.vue')['default']
    DocTable: typeof import('./../components/DocTable.vue')['default']
    FilterLabel: typeof import('./../components/index/FilterLabel.vue')['default']
    FooterBox: typeof import('./../components/footer/FooterBox.vue')['default']
    HeaderBox: typeof import('./../components/header/HeaderBox.vue')['default']
    ImageMask: typeof import('./../components/modal/ImageMask.vue')['default']
    IndexLayout: typeof import('./../components/layouts/IndexLayout.vue')['default']
    IndexList: typeof import('./../components/index/IndexList.vue')['default']
    IndexListLayout: typeof import('./../components/layouts/IndexListLayout.vue')['default']
    IndexSearchLayout: typeof import('./../components/layouts/IndexSearchLayout.vue')['default']
    LogoBasicLogo: typeof import('./../components/header/LogoBasicLogo.vue')['default']
    MainLayout: typeof import('./../components/layouts/MainLayout.vue')['default']
    MaskBox: typeof import('./../components/modal/MaskBox.vue')['default']
    ModalHost: typeof import('./../components/modal/ModalHost.vue')['default']
    NotFound: typeof import('./../components/NotFound.vue')['default']
    PhotosLayout: typeof import('./../components/layouts/PhotosLayout.vue')['default']
    RecordLayout: typeof import('./../components/layouts/RecordLayout.vue')['default']
    SearchMask: typeof import('./../components/modal/SearchMask.vue')['default']
    TRexRunner: typeof import('./../components/TRexRunner.vue')['default']
  }
}
